spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: desterminatorxd@gmail.com
    password: ygfmwvweklzwdpuh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

