spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: desterminatorxd@gmail.com
    password: {google.pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
server:
  port: 8090
