spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: desterminatorxd@gmail.com
    password: ygfmwvweklzwdpuh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
server:
  port: 8090